### ISSUE TITLE
Add missing supporter types

### ISSUE THREAD

**Issue by YummyBacon5** [mitchell-merry/src-ts#24]
[`assets.supporterIcon`](https://www.speedrun.com/api/v1/users/j033wq3j) and [`supporterAnimation`](https://www.speedrun.com/api/v1/users/j033wq3j), [`boostReceived`](https://www.speedrun.com/api/v1/games/w6jl725d) and [`boostDistinctDonors`](https://www.speedrun.com/api/v1/games/w6jl725d)
I think these might be all

**Comment by mitchell-merry** [comment]
[`UserAssets.supporterIcon`](https://github.com/mitchell-merry/src-ts/blob/521b09f6f8c66cbe4f0fb5a8dcac4aa80a8a84a9/types/src-api.ts?#L292) and [`User.supporterAnimation`](https://github.com/mitchell-merry/src-ts/blob/521b09f6f8c66cbe4f0fb5a8dcac4aa80a8a84a9/types/src-api.ts?#L299) already exist, but `Game.boostReceived` and `Game.boostDistinctDonors` are indeed missing. Thanks
