### ISSUE TITLE
Problem with webpack and packpath

### ISSUE THREAD

**Issue by DerKO9** [mitchell-merry/src-ts#67]
I have tried creating a brand new project (Create-React-App) and the only thing I have installed is src-ts. I'm getting build errors relating to webpack and packpath. The errors only show up when I try to import and use src-ts
Text:

```
Compiled with problems:

ERROR in ./node_modules/packpath/lib/packpath.js 1:9-22

Module not found: Error: Can't resolve 'fs' in 'C:\Users\Desktop\source\repos\DerKO9\src-ts-test\node_modules\packpath\lib'


ERROR in ./node_modules/packpath/lib/packpath.js 2:9-24

Module not found: Error: Can't resolve 'path' in 'C:\Users\Desktop\source\repos\DerKO9\src-ts-test\node_modules\packpath\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }


ERROR in ./node_modules/root-require/index.js 4:11-26

Module not found: Error: Can't resolve 'path' in 'C:\Users\Desktop\source\repos\DerKO9\src-ts-test\node_modules\root-require'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }
```
Picture with color:
![image](https://user-images.githubusercontent.com/17974177/200487556-1e72583a-aed0-4e75-9b6f-8003bfc814ea.png)

**Comment by mitchell-merry** [comment]
Webpack and CRA no longer include the node polyfills by default. In webpack, you have to add this to your `webpack.config.js`:
(`resolve.fallback`)
```js
fallback: {
	fs: false,
	path: require.resolve("path-browserify"),
}
```

To access these configuration files in CRA, you need to [`npm run eject`](https://github.com/facebook/create-react-app/blob/main/packages/cra-template/template/README.md#npm-run-eject). Apparently this is one-way, so be careful.

On a side note, `packpath` has caused some other issues for me in the past, so I'll consider removing it all together. It's not at all important to the project.

**Comment by mitchell-merry** [comment]
Yeah, I've removed the dependency. 2.6.3 should now work without ejecting. @DerKO9

**Comment by DerKO9** [comment]
Awesome I didnt know about the eject command and was wondering where the heck webpack.config.js was haha. I did have to install "path-browserify" for it to work, So I have added the fallback to it and I'm not getting that error anymore. I am however getting a new error that has to do with packpath.js:
![image](https://user-images.githubusercontent.com/17974177/200492656-6817a829-8246-4bb1-8ad9-c10163cd8502.png)
text
```
packpath.js:29 Uncaught TypeError: Cannot read properties of undefined (reading 'parent')
    at module.exports.parent (packpath.js:29:1)
    at requireFromModuleRoot (index.js:16:1)
    at ./node_modules/src-ts/lib/src/http.js (http.js:18:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/src-ts/lib/src/index.js (index.js:18:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
```

So I've seen this error on another CRA project I'm working which prompted me to see if this error shows up on a brand new CRA app.

**Comment by DerKO9** [comment]
> Yeah, I've removed the dependency. 2.6.3 should now work without ejecting, i.e. out of the box with create-react-app. @DerKO9

Oh I didnt see your new message. Awesome news! I really appreciate how fast you've been to reply which such a helpful answer!

**Comment by mitchell-merry** [comment]
All good! Feel free to open other issues in the future for feedback and such, I'm all ears.

If you want some documentation (i.e. use is currently not intuitive enough), I'd be happy to write that too. Just open an issue if you need something.
